service: scrobble

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  timeout: 60
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:us-east-1:*:function"

package:
  include:
    - dist/**
    - node_modules/**
  exclude:
    - src/**
    - env.yml

functions:
  plex:
    handler: dist/handler.plex
    events:
      - http:
          path: plex
          method: post
